[package]
name = "pivoterpy"
version = "2.0.0"
edition = "2021"

[lib]
name = "pivoter_rust" 
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28.3", features = ["extension-module", "num-bigint", "generate-import-lib", "abi3-py38"] }
rayon = "1.8"
fixedbitset = "0.4"
num-bigint = "0.4"
num-traits = "0.2"

[build-dependencies]
cc = "1.0"