[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "pivoterpy"
# version is specified in Cargo.toml
dynamic = ["version"] 
description = "Exact clique counting in Python and Rust, powered by the Pivoter algorithm."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE.txt"]
requires-python = ">=3.8"
dependencies = []

keywords = [
    "graph-theory", 
    "clique-counting",
    "degeneracy",
    "algorithms",
    "euler-characteristic",
    "curvatures",
    "rust"
]

classifiers = [
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Programming Language :: Rust",
    "Programming Language :: Python :: 3",
]

[project.urls]
Repository = "https://github.com/7e6i/pivoterpy"
Documentation = "https://7e6i.github.io/pivoterpy/"


[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "maturin>=1.0,<2.0",
    "networkx>=3.0",
    "numpy>=2.0",
    "patchelf>=0.17.2.4",
    "zensical>=0.0.34"
]


[tool.maturin]
python-source = "python"
module-name = "pivoterpy.pivoter_rust"
features = ["pyo3/extension-module", "pyo3/abi3-py38", "pyo3/generate-import-lib", "pyo3/num-bigint"]