[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "pivoterpy"
version = "2.0.0"
description = "Parallelized Python (and Rust) implementation of the Pivoter clique counting algorithm."
readme = "README.md"
requires-python = ">=3.8" 
dependencies = []

keywords = [
    "graph-theory", 
    "clique-counting",
    "degeneracy",
    "algorithms",
    "euler-characteristic",
    "curvatures",
    "rust"
]

classifiers = [
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Programming Language :: Rust",
    "Programming Language :: Python :: 3",
]

[project.urls]
source = "https://github.com/7e6i/Pivoter"


[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "maturin>=1.0,<2.0",
    "networkx>=3.0",
    "numpy>=2.0",
    "mkdocs-material>=9.0",
    "patchelf>=0.17.2.4"
]


[tool.maturin]
python-source = "python"
module-name = "pivoterpy.pivoter_rust"
features = ["pyo3/extension-module", "pyo3/abi3-py38", "pyo3/generate-import-lib", "pyo3/num-bigint"]