# .github/workflows/test-build.yml

name: Test Build (No Publish)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  # 1.  BUILD FOR LINUX & SOURCE CODE
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - uses: PyO3/maturin-action@v1
        with:
          manylinux: auto
          command: build
          # build source and wheel simultaneously
          args: --release --out dist --sdist 
      # Upload just the Wheel (.whl)
      - uses: actions/upload-artifact@v7
        with:
          name: wheels-linux
          path: dist/*.whl

      # Upload just the Source Code (.tar.gz)
      - uses: actions/upload-artifact@v7
        with:
          name: source-distribution
          path: dist/*.tar.gz

  # 2. BUILD FOR WINDOWS
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.8' 
          architecture: x64
      - uses: Swatinem/rust-cache@v2
      - uses: PyO3/maturin-action@v1
        with:
          command: build
          target: x64
          args: --release --out dist
      - uses: actions/upload-artifact@v7
        with:
          name: wheels-windows
          path: dist

  # 3. BUILD FOR MAC (Intel & Apple Silicon)
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - uses: PyO3/maturin-action@v1
        with:
          command: build
          target: universal2-apple-darwin
          args: --release --out dist 
      - uses: actions/upload-artifact@v7
        with:
          name: wheels-macos
          path: dist